azure-endpoint-revisit
spectrocloud/librarium pull request #1011
Opened 2022-11-30 17:14 UTC by resmaa

Added API Allocation Load Balancer to Azure Cluster creation wizard

2022-11-30 17:14 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1011#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-11-30 17:17 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 94f206a0c756253a881ef0d19a1c9888342a23a6 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1011/librarium_build/1598002699868049408) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-30 17:18 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 94f206a0c756253a881ef0d19a1c9888342a23a6 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1011/librarium_build/1598002699863855104) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-30 20:30 UTC, karl-cardenas-coding requested changes
Resma, let's take this as an opportunity to improve on this page.  Take a look at the page navigation (see the image below). There is way too much happening on one documentation page. Those are all How-to topics. We need to clean this up as we did with App Profile. Use App Profile as an example of how to restructure this section.  This page should be the overview that provides links to the other pages related to Azure. 

![CleanShot 2022-11-30 at 13 25 21](https://user-images.githubusercontent.com/29551334/204901298-ba0fb149-61ae-4d6c-a21c-727f412f5b2b.png)

2022-11-30 20:30 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure.md
>  For existing cloud account go to `Edit` and toggle the `Connect Private Cloud Gateway` option to select the created gateway from the drop down menu.
```suggestion
For existing cloud account go to **Edit** and toggle the **Connect Private Cloud Gateway** option to select the created Gateway from the drop-down menu.

```

2022-11-30 20:30 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure.md
> +Once the above information are provided to the cloud account creation wizard, click on **Disable Properties**, if the user do not want to have a network call from Palette console to the Azure account
I don't understand what is being said here. Also, we should address the user with "you" and not use a third-person voice such as "if the user."  But this paragraph needs work as it's confusing to read.

2022-11-30 20:30 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure.md
> +1. Provide the basic cluster information like **Name**, **Description** (optional), and **Tags** (optional) and select the [**Azure Cloud Account**](/clusters/public-cloud/azure#creatinganazureclouda
The last sentence is a prerequisite, so if this was structured into a How-to this would be addressed.

2022-11-30 20:30 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure.md
> +2. Select the **Cluster Profile** created for the Azure environment. The profile definition will be used as the cluster construction template and click **Next**.
```suggestion
2. Select the **Cluster Profile** created for the Azure environment. The profile definition will be used as the cluster construction template. Click on **Next**.

```

2022-11-30 20:30 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure.md
> +3. Review and override pack parameters as desired. By default, parameters for all packs are set with values defined in the Cluster Profile and click **Next**.
```suggestion
3. Review and override pack parameters as desired. By default, parameters for all packs are set with values defined in the Cluster Profile. Click **Next**.

```

2022-11-30 21:48 UTC, ritawatson requested changes

2022-11-30 21:48 UTC, ritawatson commented on content/docs/04-clusters/01-public-cloud/03-azure.md
>  New worker pools may be added if its desired to customize certain worker nodes to run specialized workloads. As an example, the default worker pool may be configured with the <i>Standard_D2_v2</i> in
```suggestion
You can add new worker pools to customize certain worker nodes to run specialized workloads. For example, the default worker pool may be configured with the <i>Standard_D2_v2</i> instance types for general-purpose workloads and another worker pool with instance type <i>Standard_NC12s_v3</i> can be configured to run GPU workloads.

```

2022-12-01 05:12 UTC, resmaa commented
> Resma, let's take this as an opportunity to improve on this page. Take a look at the page navigation (see the image below). There is way too much happening on one documentation page. Those are all How-to topics. We need to clean this up as we did with App Profile. Use App Profile as an example of how to restructure this section. This page should be the overview that provides links to the other pages related to Azure.
> 
> ![CleanShot 2022-11-30 at 13 25 21](https://user-images.githubusercontent.com/29551334/204901298-ba0fb149-61ae-4d6c-a21c-727f412f5b2b.png)

Sure we can

2022-12-01 05:15 UTC, resmaa commented
/test librarium_release_build

2022-12-01 15:41 UTC, karl-cardenas-coding approved these changes

2022-12-01 15:43 UTC, resmaa commented
/test librarium_release_build

2022-12-01 16:29 UTC, merged