pcp-516
spectrocloud/librarium pull request #1040
Opened 2022-12-14 07:26 UTC by resmaa

**Release 3.1**

Add a provision to configure Azure Storage Account from UI for images.

2022-12-14 07:26 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1040#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-14 15:17 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +While creating a custom storage account for the Azure cluster provisioned through a private gateway, disable public access to restrict access to the storage account via the gateway vNet.
@resmaa it should be VNet ☝🏻

2022-12-14 16:20 UTC, karl-cardenas-coding requested changes
Feedback and suggestions below.

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +### Cases
I'm not sure having another heading here is needed. We can include under Use Cases so that it's all together.

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +You want to have a custom storage account to be used for the following reasons:
```suggestion
You want to have a custom storage account for the following reasons:

```
Transitioned from passive to active voice.

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +The above scenario can take the following three cases:
```suggestion
The following are steps to address common scenarios related to Azure cluster storage.
```
This suggestion avoids backtracking the reader by using "above."

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +**Case 1: Default Storage Account and Storage Containers:**
```suggestion
**Usecase: Default Storage Account and Storage Containers:**

```
We can do without the numbers but let's spell out usecase.

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +**Case 2: Providing custom storage account and storage container**
```suggestion
**Usecase: Provide custom storage account and storage container**

```

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +**Case 3: Provide only the custom Azure storage account**
```suggestion
**Usecase: Custom Azure storage account**

```

2022-12-14 16:20 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +<InfoBox>
@resmaa this is a security recommendation so let's use the warning box.

2022-12-16 17:59 UTC, ritawatson commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +**Case 1: Default Storage Account and Storage Containers:**
Should Usecase be two words? **Use Case**

2022-12-16 18:01 UTC, ritawatson approved these changes
Usecase should be two words, I think.

2022-12-22 17:26 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1040#" title="Author self-approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/1040#pullrequestreview-1221252219" title="Approved">ritawatson</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/release-3-1/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-22 17:26 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | d7caee8fca0177fb6ece276aeccd7f610ac93017 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1040/librarium_build/1605977991647596544) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-22 18:28 UTC, karl-cardenas-coding commented
Closing this PR due to merge conflicts related to the restructuring.  See PR #1062

2022-12-22 18:28 UTC, closed without merging