cluster-autoscaler
spectrocloud/librarium pull request #1052
Opened 2022-12-18 15:38 UTC by resmaa

**3.1 Release Feature**

Cluster aAutoscaler
PCP-630

2022-12-18 15:38 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1052#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-18 15:44 UTC, resmaa commented
/retest

2022-12-18 16:53 UTC, resmaa commented
/retest

2022-12-19 15:53 UTC, karl-cardenas-coding requested changes
Feedback and suggestions below.

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
>  <InfoBox>
This does not need to be in an info box, it should be the heading's introductory paragraph.

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
>  ## Running Clusters through Edit Node Pool
```suggestion
## Edit Node Pool

```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**Allow worker capability (master pool)**|Select this option for allowing workloads to be provisioned on master nodes.|
```suggestion
|**Allow worker capability **|Select this option for allowing workloads to be provisioned on master nodes.|
```
We are already in the context of Master Pool, so we don't need to specify master pool.

Why do we need to

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add to constrain a Pod to only run on a particular set of Node(s).
```suggestion
|**[Labels](/clusters/cluster-management/taints#overviewonlabels)**| Add a label to apply placement constraints on a pod, such as a node eligible for receiving the workload. 

```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**Availability Zones**| Choose one or more availability zones. Palette provides fault tolerance to guard against failures like hardware failures, network failures, etc. by provisioning nodes across
```suggestion
|**Availability Zones**| Choose one or more availability zones. Palette provides fault tolerance to guard against hardware failures, network failures, etc., by provisioning nodes across availability zones if multiple zones are selected.|
```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**Enable Autoscaler**|You can enable the autoscaler, by toggling the **Enable Autoscaler** button. Autoscaler scale up and scale down the resources between the set minimum and maximum number of node
```suggestion
|**Enable Autoscaler**|You can enable the autoscaler, by toggling the **Enable Autoscaler** button. Autoscaler scales up and down resources between the defined minimum and the maximum number of nodes to optimize resource utilization.|
```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add to constrain a Pod to only run on a particular set of Node(s).
```suggestion
|**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add a label to apply placement constraints on a pod, such as a node eligible for receiving the workload.

```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**Availability Zones**| Choose one or more availability zones. Palette provides fault tolerance to guard against failures like hardware failures, network failures, etc. by provisioning nodes across
```suggestion
|**Availability Zones**| Choose one or more availability zones. Palette provides fault tolerance to guard against hardware failures, network failures, etc., by provisioning nodes across availability zones if multiple zones are selected.|
```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/01-aws.md
> +|**Disk Size**|Give the required storage size|
```suggestion
|**Disk Size**|Provide the required storage size|

```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +    |**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add to constrain a Pod to only run on a particular set of Node(s).
```suggestion
    |**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add a label to apply placement constraints on a pod, such as a node eligible for receiving the workload.

```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
> +    |**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add to constrain a Pod to only run on a particular set of Node(s).
```suggestion
    |**[Labels](/clusters/cluster-management/taints#overviewonlabels)**|Add a label to apply placement constraints on a pod, such as a node eligible for receiving the workload.

```

2022-12-19 15:53 UTC, karl-cardenas-coding commented on content/docs/04-clusters/01-public-cloud/05-gcp.md
> +  |**Enable Autoscaler**|You can enable the autoscaler, by toggling the **Enable Autoscaler** button. Autoscaler scale up and scale down the resources between the set minimum and maximum number of no
```suggestion
  |**Enable Autoscaler**|You can enable the autoscaler, by toggling the **Enable Autoscaler** button. Autoscaler scales up and down resources between the defined minimum and the maximum number of nodes to optimize resource utilization.|
```

2022-12-20 05:08 UTC, resmaa commented
/retest

2022-12-20 20:55 UTC, karl-cardenas-coding approved these changes

2022-12-20 20:55 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1052#pullrequestreview-1225122931" title="Approved">karl-cardenas-coding</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/1052#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-22 16:59 UTC, karl-cardenas-coding commented
@resmaa, I'm gonna close this PR. I went ahead and carried over the changes in a new PR #1061 that is based of the release branch. That gets us around the merge conflicts.

2022-12-22 17:00 UTC, closed without merging