fips-compliance
spectrocloud/librarium pull request #1063
Opened 2022-12-22 18:39 UTC by resmaa

**3.1 Release Feature**

FIPS Compliance

2022-12-22 18:39 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1063#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-22 19:13 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | fcc09ae01426447e623eb21b0669ca59ab440a94 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1063/librarium_build/1606003790979272704) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-23 16:04 UTC, karl-cardenas-coding requested changes
Feedback and changes. Resma, I'm confused about the tenant and project scope. It says the infra layers must be FIPS enabled. Does that mean that someone could deploy a cluster that is not FIPS enabled even though I specified I want FIPS at the platform level?

2022-12-23 16:04 UTC, karl-cardenas-coding commented on content/docs/15-compliance/00-fips-compliance.md
> +### Clouds Supported:
```suggestion
### Platforms Supported:
```
Let's not limited it to clouds as we will probably have private data centers platforms in the future.

2022-12-23 16:04 UTC, karl-cardenas-coding commented on content/docs/15-compliance/00-fips-compliance.md
> +The platform FIPS (Tenant and Project scope) can be **disabled or enabled** during cluster creation.  Toggle the **FIPS Mode** button while creating the cluster configurations of cluster deployment.
```suggestion
FIPS enablement at the tenant or project scope can be disabled or enabled during cluster creation.  Toggle the **FIPS Mode** button while creating the cluster configurations of cluster deployment.
```

2022-12-23 16:04 UTC, karl-cardenas-coding commented on content/docs/15-compliance/00-fips-compliance.md
> +<InfoBox>
```suggestion
<WarningBox>
```
This is pretty important so we should make it a warning box.

2022-12-23 16:04 UTC, karl-cardenas-coding commented on content/docs/15-compliance/00-fips-compliance.md
> +</InfoBox>
```suggestion
</WarningBox>
```

2022-12-23 16:04 UTC, karl-cardenas-coding commented on content/docs/15-compliance.md
>  The Spectro Cloud Cryptographic Module is a general-purpose cryptographic library incorporated into the Kubernetes Management Platform and Kubernetes distributions for the protection of sensitive inf
Resma, at the end of this section, we should link to the new page you are creating.

2022-12-24 11:09 UTC, resmaa commented on content/docs/15-compliance/00-fips-compliance.md
> +|Use Cases | Enable   | Mandatory Condition|
its the mandatory condition

2022-12-24 11:10 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1063#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/3.1-release-notes/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-24 11:22 UTC, resmaa commented on content/docs/15-compliance.md
> +![FIPS-Compliance](compliance_FIPS.png "#width=180px")
done

2022-12-24 16:21 UTC, karl-cardenas-coding approved these changes

2022-12-24 16:21 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1063#pullrequestreview-1229668597" title="Approved">karl-cardenas-coding</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/1063#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/3.1-release-notes/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-24 16:23 UTC, merged