Style_guide_layout_standards
spectrocloud/librarium pull request #1332
Opened 2023-05-30 14:42 UTC by rahulhazra97

## Style Guide and Layout

This PR contains all the markdown information for the Style Guide and Layout standards explained in the wiki section of Librabrium git hub.

## Review Changes

💻 [Wiki Preview](https://github.com/rahulhazra97/Documentation-Guide/wiki)

🎫 [DOC-775](https://spectrocloud.atlassian.net/browse/DOC-775)

2023-05-30 22:04 UTC, karl-cardenas-coding requested changes
Feedback and suggestions below. Two main things @rahulhazra97 

- Update the file names to all be lowercase.
- All URLs must be updated to use the librirarum wiki URLs instead of your personal repo.

2023-05-30 22:04 UTC, karl-cardenas-coding commented on styleguide/spectro-cloud-word-list.md
> +
Add an intro to this page.

2023-05-30 22:04 UTC, karl-cardenas-coding commented on styleguide/how-to.md
> +This section contains the sequential steps required to enable the feature. The steps may be console actions, commands, or scrips the user must invoke. The reader should be able to follow the steps se
Remove the internal confluence link.

2023-05-30 22:04 UTC, karl-cardenas-coding commented on styleguide/Tutorials.md
> +* To get started, make a copy of the tutorial plan [reference](https://docs.google.com/document/d/1ql_vkaj6dHsobCu0AYuvUXoQ8eojBzetAN3RoGxUepc/edit).
@rahulhazra97 let's use the tutorial plan template file and add it as a child page and link to it. Update the section respectively. 

https://docs.google.com/document/d/1ql_vkaj6dHsobCu0AYuvUXoQ8eojBzetAN3RoGxUepc/edit#

2023-05-31 19:40 UTC, rahulhazra97 commented on styleguide/Home.md
> +* [Packs Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Packs-Layout) - The Packs Layout provides an overview and guidelines for organizing and structuring packs within the document
```suggestion
* [Packs Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Packs-Layout) - The Packs Layout provides an overview and guidelines for organizing and structuring packs within the documentation. A pack refers to a collection of related components, features, or modules that are grouped together for a specific purpose or functionality. Refer to the [Packs Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Packs-Layout) to use the packs layout.
```

2023-05-31 19:41 UTC, rahulhazra97 commented on styleguide/Home.md
> +* [Packs Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Packs-Layout) - The Packs Layout provides an overview and guidelines for organizing and structuring packs within the document
```suggestion
* [Packs Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Packs-Layout) - The Packs Layout provides an overview and guidelines for organizing and structuring packs within the documentation. A pack refers to a collection of related components, features, or modules that are grouped together for a specific purpose or functionality. Refer to the [Packs Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Packs-Layout) to use the packs layout.
```

2023-05-31 22:04 UTC, karl-cardenas-coding requested changes

2023-05-31 22:04 UTC, karl-cardenas-coding commented on styleguide/spectro-cloud-style-guide.md
@rahulhazra97 Go through my original feedback for this document. Several of my suggestion and things I called out are missing.

2023-06-01 11:48 UTC, rahulhazra97 commented on styleguide/spectro-cloud-style-guide.md
I have created a list of the things you have asked me to finish for this file. I made a note yesterday while working on this. I'll share this with you when we sync-up

2023-06-01 11:50 UTC, rahulhazra97 commented on styleguide/spectro-cloud-word-list.md
> +
Added from line 3.

2023-06-01 11:51 UTC, rahulhazra97 commented on styleguide/tutorial-layout.md
> +All Spectro Cloud tutorials are expected to have the same look and feel. The tutorial text and voice must adhere to the Spectro Cloud[ style guide](https://github.com/rahulhazra97/Documentation-Guide
```suggestion
All Spectro Cloud tutorials are expected to have the same look and feel. The tutorial text and voice must adhere to the Spectro Cloud [style guide](https://github.com/rahulhazra97/Documentation-Guide/wiki/Spectro-Cloud-Style-Guide) for a universal look and feel. The tutorial layout must also feel familiar to the reader; therefore, all tutorials must follow the layout standard described on this page.
```

2023-06-01 11:53 UTC, rahulhazra97 commented on styleguide/tutorial-layout.md
> +For questions or concerns, please ask in the  Slack channel `education`.
```suggestion
For questions or concerns, please mail to our email address [spectro-docs@spectrocloud.com](spectro-docs@spectrocloud.com).
```

2023-06-01 12:57 UTC, rahulhazra97 commented on styleguide/tutorial-layout.md
> +For questions or concerns, please ask in the  Slack channel `education`.
Done.

2023-06-01 13:12 UTC, rahulhazra97 commented on styleguide/tutorial-layout.md
> +To get started with your tutorial plan, create a copy of the following template:
I did create a child page as reference template on line 20. Is that not a child page? 

Rest removed and correct to our email address.

2023-06-01 21:25 UTC, karl-cardenas-coding approved these changes
@rahulhazra97 this looks loos good. Besides the handful of suggestion I provided in this final review. Do the following things before your merge:

1. Fix the duplicate titles that is occurring in all layout pages, including the content layout page (see screenshot).

2. Fix all the URLs to make sure they don't point to your repo. You may have to add this to our actual repo as a wiki to get the real URLs.

![CleanShot 2023-06-01 at 14 23 07](https://github.com/spectrocloud/librarium/assets/29551334/7b8be1e5-a9a4-4301-a908-02d1303587d8)

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/Home.md
> +* [Troubleshooting Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Troubleshooting-Layout) - All Spectro Cloud troubleshooting guides are expected to have the same look and feel. The
```suggestion
* [Troubleshooting Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Troubleshooting-Layout) - All Spectro Cloud troubleshooting guides are expected to have the same look and feel. The guide must also feel familiar to the reader. Refer to the [Troubleshooting Layout](https://github.com/rahulhazra97/Documentation-Guide/wiki/Troubleshooting-Layout) to learn how to structure a troubleshooting guide..
```

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/tutorial-layout.md
> +To create an impactful tutorial guide, you must create a tutorial plan and obtain stakeholder approval for alignment. Adhere to the [Tutorial Plan](#tutorial-plan) section, and the [Tutorial Layout](
```suggestion
All Spectro Cloud tutorials must adhere to the following layout. Review the layout guide when structuring a tutorial. Before you bring writing a tutorial, we recommend you go through the exercise of planning out the tutorial. Use the [Tutorial Plan Template](https://github.com/rahulhazra97/Documentation-Guide/wiki/Tutorial-Plan-Template) to get started. Planning out a tutorial and identifying the scope and audience results in a higher quality deliverable and prevents writing content that may not be applicable to the tutorial. 

Reach out to us at spectro-docs@spectrocloud.com to propose a tutorial idea and share the plan with us.
```

We can combine the intro with the following section.

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/tutorial-layout.md
> +For any further information contact : `spectro-docs@spectrocloud.com
```suggestion
For any further information contact : spectro-docs@spectrocloud.com
```

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/spectro-cloud-word-list.md
> +We believe in clear and consistent communication and use this reference to reflect a unified voice and consistent messaging.  Review this list to avoid confusion, misinterpretation, or inconsistency
```suggestion
The Spectro Cloud Word List is a reference to ensure we speak the same language.  The following list is intended to help you understand the word choices we have made regarding terms commonly used in our documentation.
```

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/spectro-cloud-word-list.md
> +- prerequisite(s) - no hyphen.
```suggestion
- prerequisites - no hyphen.
```

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/troubleshooting-layout.md
> +For questions or concerns, please ask in the  Slack channel `education`.
```suggestion
For questions or concerns, email us at spectro-docs@spectrocloud.com. 
```

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/Home.md
> +
```suggestion

For questions or concerns, email us at spectro-docs@spectrocloud.com
```

Let's add a way for users to contact us at the landing page.

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/packs-layout.md
> +^ Extra blank line above!
```suggestion
```
Not sure what this is but let's remove it.

2023-06-01 21:25 UTC, karl-cardenas-coding commented on styleguide/how-to.md
> +# How-To-Guide
```suggestion
# How-to Layout
```

2023-06-02 18:49 UTC, merged