Added 4.0.13 bug fix desc for patch release
spectrocloud/librarium pull request #1562
Opened 2023-09-18 18:40 UTC by ritawatson

## Describe the Change

This PR adds release notes for patch release 4.0.13.

## Review Changes

💻 [Add Preview URL]()

🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-877)

2023-09-18 21:54 UTC, velguruswami approved these changes

2023-09-20 21:02 UTC, karl-cardenas-coding requested changes

2023-09-20 21:02 UTC, karl-cardenas-coding commented on docs/docs-content/release-notes.md
> +- Palette sometimes updates clusters when *Pause Platform Updates* is enabled at the project level. This issue is resolved. Note that although Palette did not adhere to the setting, the issue did not
```suggestion
- An issue where Palette was updating clusters when *Pause Platform Updates* was enabled at the project level is fixed. This issue did not cause nodes to repave or for clusters to become unhealthy. 
```
How about this Rita? Trying to channel my inner Rita of making things more concise 😄

2023-09-20 22:22 UTC, karl-cardenas-coding approved these changes

2023-09-20 22:32 UTC, merged