Add bug fixes and enhancements.
spectrocloud/librarium pull request #1633
Opened 2023-10-02 20:57 UTC by ritawatson

## Describe the Change

This PR adds enhancements and bug fixes for the 4.0.15 patch release.

## Review Changes

💻 [Add Preview URL]()

🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PCP-1777)
[Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-3515)
[Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-2618)
[Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-3479)
[Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-2595)

2023-10-02 23:10 UTC, karl-cardenas-coding commented
@ritawatson this does not need the 3.4 backport tag as version 4.0 content don't belong in that branch.

2023-10-03 20:00 UTC, karl-cardenas-coding requested changes
Minor suggestion

2023-10-03 20:00 UTC, karl-cardenas-coding commented on docs/docs-content/release-notes.md
> +- API calls to update edge-native machines no longer time out after 60 seconds.
```suggestion
- API calls to update edge hosts no longer time out after 60 seconds. 
```
We don't use the edge native term as it's only applicable to GE.

2023-10-03 20:00 UTC, karl-cardenas-coding commented on docs/docs-content/release-notes.md
> +  Use the `managedControlPlane.sku` parameter to specify Azure recommended settings: `Standard` for production clusters and `Free` for non-production or small clusters.
@ritawatson it feels like we are putting too much information here. Can we instead add a small heading in the Azure architecture page, document the feature, and link to it here? The Jira ticket has the YAML values, which would be good to capture.

2023-10-03 23:04 UTC, velguruswami reviewed
For PE-2595 - here is description of the fix - "The issue with showing incorrect interface of an edge host during cluster deployment is now resolved."

2023-10-03 23:58 UTC, karl-cardenas-coding approved these changes
Looks great 😄

2023-10-04 00:05 UTC, merged

2023-10-04 00:43 UTC, karl-cardenas-coding commented
@ritawatson I fixed the issue and made sure the changes got push to the `version-4-0` branch 😄