Jesse ben sso entra
spectrocloud/librarium pull request #1952
Opened 2024-01-01 23:04 UTC by Jesse-Ben

## This PR edits our docs site to include instructions on deploying SSO with Palette and Microsoft Entra ID (formerly Azure Active Directory) using OpenID Connect (OIDC). 

The instructions assist the user with SSO integration for Palette and K8s clusters.

This PR .....

## Review Changes

💻 [Add Preview URL]()

🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-489)

2024-01-02 00:21 UTC, Jesse-Ben commented on docs/docs-content/user-management/saml-sso/saml-sso.md
> +- [Palette SSO with Microsoft Entra ID OIDC](palette-sso-with-entra-id.md)
Should be "Entra".

2024-01-02 00:22 UTC, Jesse-Ben commented on docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
> +- [Microsoft Entra ID](https://entra.microsoft.com/#home) subscription. You will need an account with one of the following roles: Global Administrator, Cloud Application Administrator, Application Ad
yes.

2024-01-02 00:22 UTC, Jesse-Ben commented on docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
> +- If you want to use the same Microsoft Entra ID application for OIDC-based SSO into your Kubernetes cluster itself, you need to install [kubelogin](https://github.com/int128/kubelogin) on your local
yes

2024-01-02 00:22 UTC, Jesse-Ben commented on docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
> +- If you want to use the same Microsoft Entra ID application for OIDC-based SSO into your Kubernetes cluster itself, you need to install [kubelogin](https://github.com/int128/kubelogin) on your local
yes

2024-01-02 21:18 UTC, karl-cardenas-coding requested changes
Hi @Jesse-Ben thanks for the contribution. A couple of things that needs to be addressed first. The image count is a bit too high, we aim for a max of 12 images per page. The more images, the more of an impact it has on the load time. Let's reduce the count to 12 please.

The other issue is that the builds are not completing. Most likely it's the usage of custom HTML elements, please remove these. 

When guiding the user through pages, we don't use arrows ->. Please write out in a complete sentence where to click. For example, "Select Tenant Settings on the left Main Menu. From the Tenant Menu, select OIDC."

2024-01-17 22:45 UTC, karl-cardenas-coding commented
Closed per @Jesse-Ben 's guidance. PR #1966 carries over this work

2024-01-17 22:45 UTC, closed without merging