Header permalink
spectrocloud/librarium pull request #244
Opened 2020-10-27 16:04 UTC by iftodimihail

2020-10-27 16:04 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/244#" title="Author self-approved">iftodimihail</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-29 09:05 UTC, codrin-iftimie requested changes
generateHeadingId would not return the correct url if the header is inside a tab...
You'll see that tabs now have an identifier, which means that you can change the tab from the URL using ?<identifier>=<tab_name>. The heading url should append to this string.

Make a context provider in the tabs component so you can use it in the headings to detect the identifier and tabname

2020-10-29 09:05 UTC, codrin-iftimie commented on packages/shared/src/mdx/components/index.js
> +        onMouseLeave={() => setShowPermalink(false)}
Why not use CSS hover?

2020-11-05 07:48 UTC, codrin-iftimie requested changes

2020-11-05 07:48 UTC, codrin-iftimie commented on packages/shared/src/components/ui/Tabs.js
> +  }, [location.hash]);
[]

2020-11-05 07:48 UTC, codrin-iftimie commented on packages/shared/src/components/ui/Tabs.js
> +  }, [location.hash]);
[activeKey]

2020-11-09 11:35 UTC, codrin-iftimie approved these changes

2020-11-09 11:35 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/244#pullrequestreview-526165677" title="Approved">codrin-iftimie</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/244#" title="Author self-approved">iftodimihail</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-09 11:36 UTC, codrin-iftimie approved these changes

2020-11-09 11:36 UTC, codrin-iftimie commented on packages/shared/src/mdx/components/index.js
> +    )
DRY. You can use a HOC system to prevent code duplication.

2020-11-09 11:36 UTC, codrin-iftimie commented on packages/shared/src/mdx/components/index.js
> +    )
Merging as is for now

2020-11-09 11:36 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/244#pullrequestreview-526166247" title="Approved">codrin-iftimie</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/244#" title="Author self-approved">iftodimihail</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-09 11:36 UTC, merged