4.3 security advisories
spectrocloud/librarium pull request #2615
Opened 2024-04-12 12:02 UTC by afayasa

## Describe the Change

This PR has the list of CVEs of 4.3 security advisory

## Changed Pages

## Jira Tickets

Not applicable

## Backports

Not applicable

Can this PR be backported?
No. It is applicable only for 4.3 release.

2024-04-12 19:35 UTC, karl-cardenas-coding requested changes
Great edits @caroldelwing.  

@afayasa I left you some questions

2024-04-12 19:35 UTC, karl-cardenas-coding commented on docs/docs-content/security-bulletins/cve-reports.md
> +Low impact. The service is not exposed for public access.
@afayasa What service is this?

2024-04-12 19:35 UTC, karl-cardenas-coding commented on docs/docs-content/security-bulletins/cve-reports.md
> +No impact. The service does not accept or parse any provided user data.
@afayasa what service is this?

2024-04-12 19:35 UTC, karl-cardenas-coding commented on docs/docs-content/security-bulletins/cve-reports.md
> +Node.js IP packages before version 1.1.9 may allow Server-Side Request Forgery (SSRF). This might happen because certain
```suggestion
Node.Js IP address packages before version 1.1.9 may allow Server-Side Request Forgery (SSRF). This might happen because certain
```

2024-04-12 19:35 UTC, karl-cardenas-coding commented on docs/docs-content/security-bulletins/cve-reports.md
> +Low impact. The service is not exposed for public access.
@afayasa What service?

2024-04-12 22:11 UTC, afayasa commented on docs/docs-content/security-bulletins/cve-reports.md
> +Low impact. The service is not exposed for public access.
it is from mongo sidecar image.

2024-04-12 22:11 UTC, afayasa commented on docs/docs-content/security-bulletins/cve-reports.md
> +Low impact. The service is not exposed for public access.
mongo-sidecar

2024-04-12 22:12 UTC, afayasa commented on docs/docs-content/security-bulletins/cve-reports.md
> +No impact. The service does not accept or parse any provided user data.
sepctro-node-agent

2024-04-13 14:43 UTC, karl-cardenas-coding approved these changes

2024-04-13 14:43 UTC, merged