BET-4528
spectrocloud/librarium pull request #625
Opened 2022-03-22 11:19 UTC by resmaa

https://spectrocloud.atlassian.net/browse/BET-4528

2022-03-22 11:19 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/625#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-22 11:32 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 846581f484d43356593a7b9819f82a4c4f710034 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/625/librarium_build/1506229066770944000) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 14:19 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 295280bbe2f0518931522870f6bc1c0418d42b5f | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/625/librarium_build/1506270717262434304) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-23 03:34 UTC, resmaa commented
/retest

2022-03-23 03:49 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 295280bbe2f0518931522870f6bc1c0418d42b5f | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/625/librarium_build/1506474688069505024) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-24 04:16 UTC, resmaa commented
/retest

2022-03-24 08:18 UTC, codrin-iftimie requested changes

2022-03-24 08:18 UTC, codrin-iftimie commented on packages/docs/content/04-clusters/3-cluster-management/9-cluster-rbac.md
> +extraArgs:-
this `-` might be extra

2022-03-24 08:18 UTC, codrin-iftimie commented on packages/docs/content/04-clusters/3-cluster-management/9-cluster-rbac.md
> +```json
yaml

2022-03-24 08:18 UTC, codrin-iftimie commented on packages/docs/content/04-clusters/3-cluster-management/9-cluster-rbac.md
> +```json
yaml

2022-03-24 08:18 UTC, codrin-iftimie commented on packages/docs/content/04-clusters/3-cluster-management/9-cluster-rbac.md
> +      oidc-username-claim: "email"
lets use the same indentations as the rest (2 spaces)

2022-03-24 08:18 UTC, codrin-iftimie commented on packages/docs/content/04-clusters/3-cluster-management/9-cluster-rbac.md
> +```json
yaml

2022-03-24 10:25 UTC, codrin-iftimie approved these changes

2022-03-24 10:25 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/625#pullrequestreview-920036053" title="Approved">codrin-iftimie</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/625#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-24 10:34 UTC, merged