Free-cloud-credit #651
spectrocloud/librarium pull request #651
Opened 2022-04-11 20:56 UTC by Siboney1

New Document - free-cloud-credit

2022-04-11 20:56 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/651#" title="Author self-approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-11 20:56 UTC, spectro-prow commented
Hi @Siboney1. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-11 20:57 UTC, Siboney1 commented
Please review and approve.

2022-04-12 02:26 UTC, truegilb requested changes
Please put in this slack invite link: https://join.slack.com/t/spectrocloudcommunity/shared_invite/zt-g8gfzrhf-cKavsGD_myOh30K24pImLA

Instead of my name please say email developer@spectrocloud.com

In summary two methods: slack or email.

2022-04-12 06:09 UTC, resmaa requested changes

2022-04-12 06:09 UTC, resmaa commented on content/docs/01-introduction/6-free-cloud-credit
> +
3 mail Notifications: [**Plz check on this info if correct we can include**]
-------------------------------------------
**Usage:     Notification Send to:**
-------------------------------------------
 >50%      Tenant
>90%       Tenant
>100%     Tenant and system admin


Tenant will have access to: [**Plz check on this info if correct we can include**]
-------------------------------
**AWS account
Iamusername, password**
**access key and secret key** for resource creation purposes

2022-04-12 06:09 UTC, resmaa commented
/retest

2022-04-14 03:04 UTC, resmaa requested changes

2022-04-14 03:04 UTC, resmaa commented on content/docs/01-introduction/6-free-cloud-credit
> +
or lets not be specific to any cloud we can just go with:

Palette provides cloud account- with required credentials-  for user deployments.

2022-04-14 18:22 UTC, Siboney1 reviewed
Updated with changes

2022-04-14 18:28 UTC, resmaa approved these changes

2022-04-14 18:28 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/651#pullrequestreview-942655532" title="Approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/651#" title="Author self-approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-15 10:19 UTC, resmaa commented
closing the PR to change page location

2022-04-15 10:19 UTC, closed without merging