Doc-213-Ubuntu-v20-cc-eal-disabled
spectrocloud/librarium pull request #804
Opened 2022-07-26 15:57 UTC by Siboney1

noted cc-eal is disabled in v20

2022-07-26 15:57 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/804#" title="Author self-approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-07-26 15:58 UTC, spectro-prow commented
Hi @Siboney1. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-09 14:43 UTC, truegilb requested changes

2022-08-09 14:43 UTC, truegilb commented on content/docs/06-integrations/00-ubuntu.md
> +| **CC-EAL** | enable <br /> <br /> <br /> <br /> <br />  disable | After the completion of a Common Criteria (CC) security evaluation, a grade is given <br /> indicating the level the system was tes
"as per this documentation" - is there a link on Canonical website to reference?
"Do not make enable and install the CC artifacts." - slight word change of "make enable"?

2022-08-16 03:14 UTC, resmaa approved these changes

2022-08-16 03:14 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/804#pullrequestreview-1073444671" title="Approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/804#" title="Author self-approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-08-16 07:40 UTC, resmaa approved these changes
apprvd

2022-08-16 07:40 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/804#pullrequestreview-1073637513" title="Approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/804#" title="Author self-approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-08-17 00:09 UTC, Siboney1 reviewed
fixed

2022-08-17 23:43 UTC, truegilb requested changes
Small changes please. Overall looks good.

2022-08-17 23:43 UTC, truegilb commented on content/docs/06-integrations/00-ubuntu.md
> +3. Choose the cloud provider as the **Infrastructure provider** and click the **Next**.
and click **Next** (no the)

2022-08-17 23:43 UTC, truegilb commented on content/docs/06-integrations/00-ubuntu.md
> +Ubuntu Advantage services extend your infrastructure's security, compliance, and productivity requirements. With Palette, enable the UA services when modifying the Pack Values. See below for steps on
Is there better way to represent "With Palette, enable the UA services when modifying the Pack Values."

2022-09-07 22:42 UTC, truegilb approved these changes
Looks good.

2022-09-07 22:42 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/804#pullrequestreview-1073637513" title="Approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/804#" title="Author self-approved">Siboney1</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/804#pullrequestreview-1099899018" title="Approved">truegilb</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-09-07 22:42 UTC, merged

2022-09-08 01:05 UTC, truegilb approved these changes
Looks good.

2022-09-08 01:06 UTC, truegilb reviewed
Looks good.