DOC-251-Nested-Cluster
spectrocloud/librarium pull request #854
Opened 2022-08-30 03:12 UTC by Siboney1

Nested Cluster and Quickstart page

2022-08-30 03:12 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/854#" title="Author self-approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-08-30 03:12 UTC, spectro-prow commented
Hi @Siboney1. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-30 03:13 UTC, Siboney1 commented
Includes Nested Cluster and Quickstart

2022-08-30 14:01 UTC, TylerGillson reviewed
Couple of minor nits... looks great overall though!

2022-08-30 16:33 UTC, tiwarisumit3 commented on content/docs/04-clusters/4-nested-clusters.md
> +Nested Clusters are Kubernetes clusters that run within an existing cluster (also known as a host cluster) and share select resources. They are lightweight, cost-effective, secure, and resource effic
nit pick: share selected resources?

2022-08-30 16:37 UTC, tiwarisumit3 commented on content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
> +- Ensure you have a functioning cluster already configure. Refer to the [New Clusters](/clusters/new-clusters) page for more information.
1. Enable the nested cluster option needs to be enabled from the settings tab.

2. Cluster should be launched with this settings.

2022-08-31 14:26 UTC, TylerGillson commented on content/docs/04-clusters/4-nested-clusters.md
> +  - The NGINX Ingress Controller must be deployed on the Host cluster with the SSL pass through enabled. This allows TLS termination to occur at the Nested Cluster's Kubernetes API server.
should be: "with SSL passthrough enabled"

2022-08-31 14:26 UTC, TylerGillson commented on content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
> +   1. When you [create](/clusters/new-clusters) and [deploy](/clusters/nested-clusters/cluster-quickstart#deployinganestedcluster) a new Host Cluster, there is an option to **Enable Nested Clusters**
"below are available, when you are enabling" - no comma needed. Should be "below are available when you are enabling"

2022-08-31 14:26 UTC, TylerGillson commented on content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
> +   2. Similarly, you can [enable](/clusters/nested-clusters/cluster-quickstart#enablinganestedclusteronahostcluster) an existing cluster and configure it to become a Nested Cluster.
"an existing cluster and configure it to become a Nested Cluster." --> "an existing cluster and allow it to host Nested Clusters."

2022-08-31 14:26 UTC, TylerGillson commented on content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
> +   3. Or, you can import a [Brownfield Cluster](/clusters/brownfield-clusters#importingabrownfieldcluster) and then, enable the Nested Cluster.
"and then, enable the Nested Cluster." --> "and then enable it to host Nested Clusters."

2022-08-31 14:26 UTC, TylerGillson commented on content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
> +3. Set the **Quota Limits** for the following hardware settings:
As of last night, quotas are being removed for 2.8

2022-08-31 18:51 UTC, truegilb requested changes
Overall looks great - as mentioned please remove quota from the description as it's the latest update that needs to happen in 2.8.

2022-08-31 18:59 UTC, TylerGillson requested changes

2022-08-31 18:59 UTC, TylerGillson commented on content/docs/04-clusters/4-nested-clusters/nested-cluster-quickstart.md
> +- Deploy the NGINX Ingress Controller on the Host Cluster and ensure that the SSL passthrough is enabled in the NGINX Ingress Controller pack's values.yaml. Specifically, charts.ingress-nginx.control
should be "ensure that SSL passthrough is enabled"

2022-08-31 22:06 UTC, tiwarisumit3 approved these changes

2022-08-31 22:06 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/854#" title="Author self-approved">Siboney1</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/854#pullrequestreview-1092564149" title="Approved">tiwarisumit3</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-08-31 22:07 UTC, tiwarisumit3 commented
Apart from minor comments from Tyler to be addressed, overall it looks good to me. Thanks Dorris.

2022-09-01 18:58 UTC, truegilb approved these changes

2022-09-01 18:58 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/854#" title="Author self-approved">Siboney1</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/854#pullrequestreview-1092564149" title="Approved">tiwarisumit3</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/854#pullrequestreview-1093910754" title="Approved">truegilb</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-09-02 16:00 UTC, TylerGillson approved these changes

2022-09-02 17:25 UTC, merged