cloudanix
spectrocloud/librarium pull request #913
Opened 2022-10-10 18:24 UTC by resmaa

cloudanix pack

2022-10-10 18:24 UTC, spectro-prow commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/913#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-10-10 18:24 UTC, spectro-prow commented
Hi @resmaa. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-11-11 06:42 UTC, mpurusottamc commented
@zulfilee Can you please review the PR?

2022-12-13 20:35 UTC, karl-cardenas-coding requested changes
Feedback and comments below.

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix helm chart supports the following versions with Palette.
```suggestion
Cloudanix Helm Chart supports the following versions with Palette.
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +Users can initiate workflows (Jira integration) and target specific workloads (excluding container, pod, or node while performing an anti-pattern) right from the Cloudanix Dashboard. This helm chart
```suggestion
Users can initiate Jira workflows and target specific workloads, excluding containers, pods, or nodes, right from the Cloudanix Dashboard. This Helm Chart installs three Cloudanix services to enable container security capabilities. The services are listed below:
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix container security add-on detects threats and abnormal behaviors in the Kubernetes clusters. Cloudanix Dashboard visualizes:
```suggestion
Cloudanix container security add-on detects threats and abnormal behaviors in Kubernetes clusters. The Cloudanix dashboard visualizes the following:
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +* Mapping the threats to Workloads (container, pod, node, etc.)
```suggestion
* Mapping the threats to workloads in containers, pods, nodes, etc.
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +* The user who initiated the threat, and much more..
```suggestion
* The user who initiated the threat, and much more.
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +* The raw command executed
```suggestion
* The command that initiated or created the thread
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +## Prerequisites
```suggestion
# Prerequisites
```

2022-12-13 20:35 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +## Prerequisites
@resmaa prerequisites should be at the top. This is information the reader should be exposed to early on, so let's move it to the top.

2022-12-14 07:50 UTC, ajinkya1986 commented
@resmaa Can you address the PR comments

2023-03-22 17:29 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* The Kubernetes version 1.15.x and above
```suggestion
* Kubernetes 1.15.x and higher
```

2023-03-22 17:50 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* Minimum Memory Required: 25 MiB
```suggestion
* Memory: 25 MiB
```

2023-03-22 17:54 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix Helm Chart supports the following versions with Palette.
This line can be deleted.

2023-03-22 17:55 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +
Delete lines 58-60. We're no longer listing versions like this.

2023-03-22 17:55 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* Minumum CPU Cores: 1
```suggestion
* CPUs: 1
```

2023-03-22 17:58 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +metaDescription: 'Cloudanix container security helm chart for Spectro Cloud Palette'
```suggestion
metaDescription: 'Helm chart pack that provides security for Cloudanix containers in Palette'
```

2023-03-22 18:03 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix container security add-on detects threats and abnormal behaviors in Kubernetes clusters. The Cloudanix dashboard visualizes the following:
```suggestion
The Cloudanix pack is an add-on security pack that provides a dashboard to help you detect threats and abnormal behavior in your Kubernetes clusters. The Cloudanix dashboard displays the following:
```

2023-03-22 18:12 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* Associated events for the threats
```suggestion
* Events associated with a threat
```

2023-03-22 18:13 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* Mapping the threats to workloads in containers, pods, nodes, etc.
```suggestion
* A mapping of threats to workloads in containers, pods, and nodes.
```

2023-03-22 18:14 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* The command that initiated or created the thread
```suggestion
* The command that caused the threat to occur.
```

2023-03-22 18:20 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +* The user who initiated the threat, and much more.
```suggestion
* The user who initiated the activity that caused the threat.
```

2023-03-22 18:22 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +Users can initiate Jira workflows and target specific workloads, excluding containers, pods, or nodes, right from the Cloudanix Dashboard. This Helm Chart installs three Cloudanix services to enable
```suggestion
Users can start Jira workflows and target specific workloads, excluding containers, pods, or nodes, from the Cloudanix Dashboard. The Cloudanix Helm Chart installs three Cloudanix services to enable container security capabilities:
```

2023-03-22 18:24 UTC, ritawatson commented on content/docs/06-integrations/00-cloudanix.md
> +
Add boldface to these.

2023-03-22 18:26 UTC, ritawatson reviewed
I did a quick copy-edit. When you've added these comments, I can pull the branch and apply the pack layout to it.

2023-03-23 07:17 UTC, ajinkya1986 commented
Hi @ritawatson. I have made the changes and added examples for threat and unusual behavior. I have sent you the file on slack. Can you please review.

2023-03-23 15:23 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | e60692ec2795b8d4cfc94210f20a4893afd5288b | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/913/librarium_build/1638921420392108032) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-23 15:26 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 88805d7991c4e140cd7c3c64aaddda9c928f1019 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/913/librarium_build/1638922049952944128) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-23 15:27 UTC, spectro-prow commented
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | e47cc4f86b3dd7b84d12d7917df66a3bd5834a9e | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/913/librarium_build/1638924568846405632) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-27 16:59 UTC, karl-cardenas-coding approved these changes
👍🏻

2023-03-27 16:59 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +  type = "operator-instance"
```suggestion
  type = "helm"
```

2023-03-27 16:59 UTC, karl-cardenas-coding commented on content/docs/06-integrations/00-cloudanix.md
> +- Writes below a binary directory.
```suggestion
- Detecting files added or modified in sensitive directories.
```

2023-03-27 18:37 UTC, merged